variables:
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_DRIVER: overlay2

# Official docker compose image.
image:
  name: docker/compose:1.24.1
  entrypoint: ["/bin/sh", "-c"]

services:
  - docker:dind

build:
  stage: build
  tags:
    - GameBase
  script:
    - docker version
    - docker-compose version
    - docker-compose build