image: docker:19.03.4

services:
  - docker:19.03.4-dind
stages:
  - build
  - push
variables:
  DOCKER_TLS_CERTDIR: ""

Build image:
  stage: build
  tags:
    - GameBase
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest ubuntu

Upload:
  stage: push
  tags:
    - GameBase
  script:
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest