image: docker:19.03.1

services:
  - docker:19.03.1-dind

stages:
  - build
  - push

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  #DOCKER_TLS_CERTDIR: ''
  DOCKER_HOST: tcp://docker:2376
  DOCKER_DRIVER: overlay2

before_script:
  - echo $CI_REGISTRY_USER
  - echo $CI_REGISTRY
  - netstat -tulpn
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

Build image:
  stage: build
  tags:
    - GameBase
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest ubuntu

Upload:
  stage: push
  tags:
    - GameBase
  script:
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest