image: docker/compose:1.24.1

stages:
  - build

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_IMAGE_NAME: $CI_REGISTRY/$CI_REGISTRY_IMAGE

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

Build image:
  stage: build
  tags:
    - GameBase
  variables:
    IMAGE_VERSION_TAG: $CI_COMMIT_SHA
  script:
    - docker pull $DOCKER_IMAGE_NAME:$IMAGE_VERSION_TAG || true
    - docker-compose build
    - docker-compose push