image: docker:stable-dind

services:
  - docker:stable-dind

stages:
  - build
  - push

variables:
  #DOCKER_HOST: tcp://docker:23780/
  DOCKER_DRIVER: overlay2

before_script:
  - echo $CI_REGISTRY_USER
  - echo $CI_REGISTRY
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

Build image:
  stage: build
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest ubuntu

Upload:
  stage: push
  script:
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest