variables:
  DOCKER_DRIVER: overlay2

# Official docker compose image.
image:
  name: docker/compose:1.24.1
  entrypoint: ["/bin/sh", "-c"]

services:
  - docker:dind

build:
  stage: build
  tags:
    - GameBase
  script:
    - netstat -tulpn
    - docker version || true
    - docker-compose version || true
    - docker-compose build